name: Deploy develop on merge
on:
  pull_request:
    branches:
    - develop
    - production
    - staging 
    - opsbranch 
    #types: [closed] # check pr is closed

jobs:
  build_zip_deploy:
    #if: ${{ github.event.pull_request.merged }}  # check PR is merged nad closed
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3 # fetch latest commit
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: |
        cd ./DSider
        echo $pwd
        dotnet restore
    - name: Publish
      run: |
        cd ./DSider
        echo $pwd
        dotnet publish --configuration Release -o site
    - name: Zip Site
      run: |
        cd ./DSider/site
        echo $pwd
        Compress-Archive -Path ./* -DestinationPath ../site.zip
        cd ..
        Compress-Archive -Path "site.zip", "aws-windows-deployment-manifest.json" -DestinationPath "deploy.zip"
    - name: Check Branch develop
      env:
          BRANCH_NAME: ${{github.ref}}
      if: (BRANCH_NAME == 'develop')
      run: |
          ENV_NAME= 'DSiderInc-dev'
          APP_NAME= 'DSiderInc'
    - name: Check Branch production
      env:
          BRANCH_NAME: ${{github.ref}}
      if: (BRANCH_NAME == 'production')
      run: |
          ENV_NAME= 'DSiderinc-prod'
          APP_NAME= 'DSiderinc-prod'
    - name: Check Branch staging
      env:
          BRANCH_NAME: ${{github.ref}}
      if: (BRANCH_NAME == 'staging')
      run: |
          ENV_NAME= 'DSiderinc-stage'
          APP_NAME= 'DSider'
    - name: Check Branch Opsbranch
      env:
          BRANCH_NAME: ${{github.ref}}
      if: (BRANCH_NAME == 'opsbranch')
      run: |
          ENV_NAME= 'DSideropstest-dev'
          APP_NAME= 'DSideropstest'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: APP_NAME
        environment_name: ENV_NAME
        version_label: v${{ steps.date.outputs.date }}
        region: us-east-1
        deployment_package: DSider/deploy.zip
