name: Deploy develop on merge
on:
  pull_request:
    branches:
    - develop
    #types: [closed] # check pr is closed

jobs:
  build_zip_deploy:
    #if: ${{ github.event.pull_request.merged }}  # check PR is merged nad closed
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3 # fetch latest commit
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: |
        cd ./DSider
        echo $pwd
        dotnet restore
    - name: Publish
      run: |
        cd ./DSider
        echo $pwd
        dotnet publish --configuration Release -o site
    - name: Zip Site
      run: |
        cd ./DSider/site
        echo $pwd
        Compress-Archive -Path ./* -DestinationPath ../site.zip
        cd ..
        Compress-Archive -Path "site.zip", "aws-windows-deployment-manifest.json" -DestinationPath "deploy.zip"
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: AKIA2NWMPB72LIDOX4RP
        aws_secret_key: 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
        application_name: DSiderInc
        environment_name: DSiderInc-dev
        version_label: 1.${{ github.event.id }}
        region: us-east-1
        deployment_package: deploy.zip
