name: Deploy develop on merge
on:
  pull_request:
    branches:
    - develop
    - staging 
    - opsbranch 
    #types: [closed] # check pr is closed

jobs:
  build_zip_deploy:
    #if: ${{ github.event.pull_request.merged }}  # check PR is merged nad closed
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3 # fetch latest commit
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: |
        cd ./DSider
        echo $pwd
        dotnet restore
    - name: Publish
      run: |
        cd ./DSider
        echo $pwd
        dotnet publish --configuration Release -o site
    - name: Zip Site
      run: |
        cd ./DSider/site
        echo $pwd
        Compress-Archive -Path ./* -DestinationPath ../site.zip
        cd ..
        Compress-Archive -Path "site.zip", "aws-windows-deployment-manifest.json" -DestinationPath "deploy.zip"
    - name: Testing branch name format
      run: echo ${{ github.base_ref }}
    - name: Check Branch opsbranch
      id: vars
      if:  ${{ github.base_ref == 'opsbranch' }}
      run: |
        echo "ENV_NAME=DSideropstest-dev" >> $GITHUB_ENV
        #echo  "::set-output name=ENV_NAME::$(env_name)"
    - name: Testing variables 
      run: |
        echo  "The variable is ${{ env.ENV_NAME }}"
    - name: Check Branch develop
      if:  ${{ github.ref == 'develop' }}
      run: echo "Check Branch develop"
      env:
        ENV_NAME: DSiderInc-dev
        APP_NAME: DSiderInc
    - name: Check Branch staging
      if:  ${{ github.ref == 'refs/heads/staging' }}
      run: echo "Check Branch staging"
      env:
        ENV_NAME: DSiderinc-stage
        APP_NAME: DSider
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: ${{ env.app_name }}
        environment_name: ${{ env.env_name }}
        version_label: v${{ steps.date.outputs.date }}
        region: us-east-1
        deployment_package: DSider/deploy.zip
